[package]
name = "curve_similarities"
authors = ["nucccc <dan.dom.nuc@gmail.com>"]
version = "0.4.0"
homepage = "https://github.com/nucccc/curve_similarities"
documentation = "https://docs.rs/curve_similarities"
repository = "https://github.com/nucccc/curve_similarities"
edition = "2021"

license = "MIT"

readme = "readme.md"

description = "Calculation of curve similarities for nd-array"

keywords = ["mathematics", "science", "numerical", "curve", "calculations"]
categories = ["mathematics", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.3.2"
ndarray = "0.16.0"
ndarray-interp = "0.5.0"
ndarray-stats = "0.6.0"
num = "0.4.3"